### ISSUE TITLE
Tab navigation component

### ISSUE THREAD

**Issue by palakgupta2712** [RealDevSquad/mobile-app#10]
- User will be able to see the tab navigation in my site.
<img width="183" alt="image" src="https://user-images.githubusercontent.com/61227144/149638055-4f576bed-7304-4c8f-8d49-70c8e9cb33e5.png">

**Comment by vinayak-trivedi** [comment]
@palakgupta2712  instead of having it like this we can have bottom navigation as it would be better for mobile apps.

**Comment by vvaibhavdesai** [comment]
Maybe we can have icons instead of text that would look much better

**Comment by palakgupta2712** [comment]
We are removing this feature and going to add bottom navigation instead.
