### ISSUE TITLE
Create a script for sanity checks before committing code

### ISSUE THREAD

**Issue by sakshambhatt** [RealDevSquad/mobile-app#105]
Write a script `precommit-check` which does the following:
1. yarn run format-fix
2. yarn run lint -> so that linting errors and warning can be eliminated
3. yarn run test -> so that one can see and fix failing tests before committing, as it will be stopped at CI stage later

**Comment by shreya-mishra** [comment]
@sakshambhatt are you doing this task? Will you please mention the ETA here?

**Comment by sakshambhatt** [comment]
Yes, I am doing this one. Will raise a PR tomorrow

**Comment by sakshambhatt** [comment]
I have raised [PR #117](https://github.com/Real-Dev-Squad/mobile-app/pull/117) for this issue. Please take a look.

**Comment by shreya-mishra** [comment]
Merged to Develop branch !
