### ISSUE TITLE
Feat/Goal screen : create a floating button 

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#120]
Feature task 👍 

Create a floating button with three options - assigned goal, a new goal, and todo. 

wireframe : 

![image](https://user-images.githubusercontent.com/61110378/177180422-7f61ee35-41fe-459e-8fd3-c3b436794ecd.png)

icons 👍 
https://iconduck.com/

**Comment by priyanshk20** [comment]
I'm taking this

**Comment by shreya-mishra** [comment]
Test incomplete

ETA - 23/09/22
