### ISSUE TITLE
Goal Screen: Home page Long term Goals section

### ISSUE THREAD

**Issue by vinayak-trivedi** [RealDevSquad/mobile-app#128]
Create the Long Term goals section component of goal screen.

Design⬇️
![longterm](https://user-images.githubusercontent.com/90315175/178665249-b32b0065-bf05-4925-86bd-767e37ddb929.jpg)

**Comment by dakshbhardwaj** [comment]
i want to work on this issue

**Comment by shreya-mishra** [comment]
> i want to work on this issue

assigned to you
