### ISSUE TITLE
Sign in through web  (UI)

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#139]
Create a button to **Sign in with the web** below the **Sign in with GitHub** button. It should open a bottom sheet popup with one text box that will take OTP from the user.

**Comment by bajajcodes** [comment]
I want to take this issue.

**Comment by shreya-mishra** [comment]
assigned !!!!! ETA ??

**Comment by bajajcodes** [comment]
> assigned !!!!! ETA ??

23/09/22

**Comment by shreya-mishra** [comment]
https://github.com/Real-Dev-Squad/mobile-app/pull/141/files

under review
