### ISSUE TITLE
Create a Form

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#163]
To create a goal or task creation form, we need to include several fields that gather the necessary information. The form should ask the user for a "Title," which will briefly summarize the goal or task. It should also prompt for a "Description" field, which allows the user to provide more details about the goal or task.

In addition to these fields, the form should ask for "Duration," which specifies the amount of time the user plans to spend working towards the goal or completing the task. Finally, the form should include a "Deadline" field, which indicates the date and time by which the user aims to finish the goal or task.

By gathering all of this information in a single form, users can easily create and keep track of their goals and tasks, and ensure they are on track to achieving them.

Figma 
![image](https://user-images.githubusercontent.com/61110378/234731197-ed50ef59-1254-4d13-b2e0-69e8c97596ed.png)

PS: for now Associated Term goal and visibility not needed

**Comment by shreya-mishra** [comment]
ETA 5th May

**Comment by JAYATEJA04** [comment]
ETA would be 5-MAY-2023.
