### ISSUE TITLE
Design Fix : Logout button styling 

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#168]
The alignment of the Logout button within the profile tab needs adjustment. Please address the alignment issue for the Logout button on the profile tab.

**Comment by Subham5401** [comment]
Hey @shreya-mishra, I'd like to take this further.

**Comment by tushartiwari7** [comment]
> The alignment of the Logout button within the profile tab needs adjustment. Please address the alignment issue for the Logout button on the profile tab.

I can take this too.
