### ISSUE TITLE
 Integration of POST API call to create a new goal in Goals App

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#170]
I would like to request the integration of a POST API call in the Goals App to enable the creation of new goals.

**BASE_URL** : https://backend-goals-production.up.railway.app

**API Endpoint** : {{BASE_URL}}/goal/

**Body** :
 ```
{
    "data": {
        "type": "Goal",
        "attributes": {
            "title": "Test Title 2"
        }
    }
}
```
**NOTE**:  Please ensure that the necessary authentication and authorization mechanisms are in place to secure the API endpoint and protect user data.  For the auth please refer below Postman collection link  
 https://api.postman.com/collections/18992903-eefca41f-d1e9-40dc-8dfa-b17920badb79?access_key=PMAT-01GZBS0MW8KH0VC5SWWSWK601S
 
 Ping in channel in case of any confusion.

**Comment by JAYATEJA04** [comment]
ETA would be 18/06/2023.
@shreya-mishra

**Comment by shreya-mishra** [comment]
Assigned !

**Comment by JAYATEJA04** [comment]
The new ETA for this task would be 24/06/2023.

**Comment by JAYATEJA04** [comment]
Need some more time as I was dealing with the issues raised in my previous task. I have never worked with API and I'm currently exploring them, the new ETA would be 28/06/2023.
