### ISSUE TITLE
Enhancement of Profile Page

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#188]
We need an enhancement of our profile, giving the read-only text of user details. I won't get change.  To get the design view you can get it from https://members.realdevsquad.com/bhavika-tibrewal the `m-site`

**Comment by harshith-venkatesh** [comment]
Are we expected to build member site profile page in RN?

**Comment by shreya-mishra** [comment]
> Are we expected to build member site profile page in RN?

yup, it is going to be profile page of our user who has logged In , but it will look like our member's page profile.

**Comment by JAYATEJA04** [comment]
I will work on this, please assign this to me.
@shreya-mishra

**Comment by JAYATEJA04** [comment]
ETA would be 25/07/2023.
