### ISSUE TITLE
Get the user's data from the GET api 

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#189]
Integrate the GET api call to get the user's data on the profile page.

please confirm the api from @pallabez or @lakshayman once.

**Comment by mohammadkhizerkhan** [comment]
Hi @shreya-mishra  i want to work on this. assign it to me please

**Comment by shreya-mishra** [comment]
Assigned ! Explore this once and let me know the ETA please

**Comment by pallabez** [comment]
API - 
https://api.realdevsquad.com/users

**Comment by shreya-mishra** [comment]
> API - https://api.realdevsquad.com/users

https://members.realdevsquad.com/ankush, @pallabez we are building this page in mobile app, isnt it `/self` api

below will be the response 
<img width="849" alt="image" src="https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/f2cc2907-b623-4dce-870e-4568b594024a">
<img width="530" alt="image" src="https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/ee5e1a1d-2507-4385-8f51-a3b2939207be">

@pallabez please confirm!!

**Comment by shreya-mishra** [comment]
> > API - https://api.realdevsquad.com/users
> 
> https://members.realdevsquad.com/ankush, @pallabez we are building this page in the mobile app, isn't it `/self` API
> 
> below will be the response <img alt="image" width="849" src="https://user-images.githubusercontent.com/61110378/250119778-f2cc2907-b623-4dce-870e-4568b594024a.png"> <img alt="image" width="530" src="https://user-images.githubusercontent.com/61110378/250119841-ee5e1a1d-2507-4385-8f51-a3b2939207be.png">
> 
> @pallabez please confirm!!

Discussed! We have two APIs

for the user data
https://api.realdevsquad.com/users?id={user-id}
for contributions
https://api.realdevsquad.com/contributions/username

**Comment by shreya-mishra** [comment]
Need to integrate Redux Saga so that we can use user's data globally !

**Comment by mohammadkhizerkhan** [comment]
@shreya-mishra ETA will be 09 July 2023
