### ISSUE TITLE
RFC: Step by step process for uploading the build on playstore

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#208]
**Date**: August 23, 2023
Authors: @kotesh-arya 
**Status**: Draft

## Abstract:
This RFC outlines a comprehensive step-by-step process for  successfully uploading a mobile app build on the Google Play Store. It provides clear instructions and guidelines to ensure a smooth and error-free deployment process.
            
 ## Introduction:
Uploading a mobile app build to the Google Play Store is a crucial step in making your app available to millions of users. This document serves as a guide for developers, detailing the necessary steps and best practices to follow during the submission process. 

## Prerequisites:
Before proceeding with the upload process, it should be ensured to have the following prerequisites in place:       

- A Google Play Developer Account.
Step-1: Open this link in your browser : https://play.google.com/console/about/
 
![Step-0_Playstore-upload](https://github.com/Real-Dev-Squad/mobile-app/assets/69259490/d52c5eb0-826f-4ca0-83fb-f4714738ae11)
Click on `Go to Play Console`

Step-2: Fill the required details
![Playstore-upload-app-build-1](https://github.com/Real-Dev-Squad/mobile-app/assets/69259490/23b1f05f-4e67-4fca-b6d2-c19b955f0038)

Step-3: Select your Interests
![Playstore-upload-2](https://github.com/Real-Dev-Squad/mobile-app/assets/69259490/2bf47ab5-f0f4-41c3-9403-9d29db9928e1)

Step-4: Click on Finish
![playstore-upload-step3](https://github.com/Real-Dev-Squad/mobile-app/assets/69259490/e49e3966-295a-43f0-b1ce-72ca29627cdf)

Now you should be able to details on a dedicated dashboard
![playstore-upload-build-4](https://github.com/Real-Dev-Squad/mobile-app/assets/69259490/cc896299-ef12-4711-b1d1-7e4727b9f8f5)

- A signed and properly configured APK (Android Package) or App Bundle of the app build.
- Graphics assets, including app icons, screenshots, and promotional images.
- A thorough testing phase to identify and resolve any issues.

## Main Process:
**Step-1: Prepare Store Listing**
- Log in to your Google Play Developer Console.
- Select the app you want to publish or create a new app entry.
- Enter the app's title, short description, full description, and select appropriate categories and tags.
- Upload high-quality app icons, feature graphics, and screenshots to showcase the app's interface and functionality.
- Add a promotional video (if available) to give users a preview of the app's features.

**Step-2: Configure Pricing and Distribution**
Google has a **one-time $25 registration fee** which you need to pay before you can upload an app. Google says it encourages higher quality products, i.e. less SPAM. If you don’t like the idea, then it helps to look at Apple’s and Microsoft’s policies for their app stores. Apple charges **$99 per year**. Microsoft charges **between $19 and $99 per year**, depending on the account type.

- Choose whether your app will be free or paid, and set the appropriate price.
- Configure distribution options for specific countries or regions if necessary.
- Specify age restrictions and content ratings based on your app's content.

**Step-3: Upload APK or App Bundle**
- In the "App releases" section, click "Create release."
- Choose whether to upload an APK or an App Bundle. If using an App Bundle, Google Play will generate optimized APKs for different device configurations.
- Upload the APK or App Bundle and ensure it is signed with the appropriate keystore.
- Add release notes to inform users about the changes in this version.
- Review and confirm the release.

**Step-4: Testing**
- Opt for the internal testing track to allow limited users (testers) to access the app before its public release.
- Invite testers using their Google accounts or using a testing link.
- Testers can provide feedback, report issues, and help ensure the app's quality.

**Step-5: Review and Rollout**
- For production releases, submit the app for review by clicking "Start rollout to production."
- Google Play's automated review process will check for policy compliance and potential issues. Address any flagged issues promptly.
- Monitor the rollout progress and user feedback.

**Step-6: Post-Release**
- Regularly monitor user reviews and feedback.
- Address issues and release updates as needed.
- Utilize Google Play Console's analytics to gain insights into user behaviour and app performance.

**Comment by kotesh-arya** [comment]
Hey @shreya-mishra 
Can you assign me this task ?
