### ISSUE TITLE
Test For Profile Screen

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#21]
Test For Profile Screen using Jest

**Comment by shreya-mishra** [comment]
we have done with the profile screen , please take a pull and complete the  test . If you are not available please raise the draft Pr so that others can do it 🙂

**Comment by DeRaowl** [comment]
Hi Shreya, I would like to work on this issue

**Comment by shreya-mishra** [comment]
I am not able to assign you the ticket, I guess you are not the part of RDS organization. Can you ask Ankush for the same? Btw you can also start working on the same ticket.

**Comment by shreya-mishra** [comment]
can you give the Eta for the same?
