### ISSUE TITLE
OOO Form  Design Enhancement

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#218]
**Design** 
![image](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/7ff24139-3eee-4ab8-9931-1119b28a73c1)

To get the form, simply perform a checkout from the [PR](https://github.com/Real-Dev-Squad/mobile-app/pull/216) branch. 

If you face any challenges, kindly share them on the #react-native-channel. Also, feel free to participate in our daily standup meeting at 9pm.

**Comment by harshitadatra** [comment]
please assign this task to me

**Comment by shreya-mishra** [comment]
ETA
