### ISSUE TITLE
Report bugs and Improvements

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#221]
We are aware that there we need improvement, and we are committed to addressing these issues. We welcome your input and collaboration. Feel free to identify any bugs and improvement by leaving comments, and if you're interested in addressing any of them, please let us know.

- [x] #321
- [x] #322
- [x] #323
- [x] #324
- [x] #325
- [x] #326
- [x] #327

**Comment by shreya-mishra** [comment]
someting went wrong sould fix

picutres allow
toast msg should within the bound of the screen
button - design system

**Comment by shreya-mishra** [comment]
- [x] https://github.com/Real-Dev-Squad/mobile-app/issues/223 - **Must Needed**
- [x] https://github.com/Real-Dev-Squad/mobile-app/issues/224 - **Must Needed**
- [x] https://github.com/Real-Dev-Squad/mobile-app/issues/226
- [x] https://github.com/Real-Dev-Squad/mobile-app/issues/225
- [x] https://github.com/Real-Dev-Squad/mobile-app/issues/227

**Comment by dhruv036** [comment]
Issues found RDS 1.0(1) version 
1. Before invoking camera permission scanner is visible. Ideally it doesn't show.

https://github.com/Real-Dev-Squad/mobile-app/assets/56362412/e90bfa50-a21d-49af-b5b3-830af5ce7398


2. After not allowing permission multiple time we should show some msg to allow permission.

https://github.com/Real-Dev-Squad/mobile-app/assets/56362412/dbe97876-5656-42f0-a077-6057b7f20472


4. Not able to logout.

https://github.com/Real-Dev-Squad/mobile-app/assets/56362412/7dfb2705-774d-4ec1-8e66-8a19c45d4244

5. UI issue in profile section(color and empty box)

https://github.com/Real-Dev-Squad/mobile-app/assets/56362412/a51008f5-0b9f-4d06-bb9a-c5d3e8db86e7

ETA: 08/11/23

**Comment by shreya-mishra** [comment]
> Issues found RDS 1.0(1) version
> 
>     1. Before invoking camera permission scanner is visible. Ideally it doesn't show.
> 
> 
> WhatsApp.Video.2023-11-01.at.1.58.23.AM.mp4
> 
>     2. After not allowing permission multiple time we should show some msg to allow permission.
> 
> 
> WhatsApp.Video.2023-11-01.at.2.12.46.AM.mp4
> 
>     4. Not able to logout.
> 
> 
> WhatsApp.Video.2023-11-01.at.1.58.10.AM.mp4
> 
>     5. UI issue in profile section(color and empty box)
> 
> 
> WhatsApp.Video.2023-11-01.at.1.58.17.AM.mp4
> 
> ETA: 08/11/23

**Comment by shreya-mishra** [comment]
- [ ] the issue is not in allowing permission , the only issue which I can see is the alert message which we show, it should just say that please allow the permission for camera , that's it.
- [ ] home screen when we fill the form of ooo , then you should clear the form once it is added, and also change the color of button , it looks like it is disabled.
- [ ] At bottom nav bar the section of particular home icon and text is too small , it should be bigger (we can adjust it with padding)
- [ ] we should move the logout button and update option  under profile avatar.
- [ ] We should remove noteworthy contributions, it is not needed.
- [ ] check the response time of the api of all tasks and active tasks 
- [ ] fix the loader and response time while fetching active tasks.

**Comment by dhruv036** [comment]
> * [x]  home screen when we fill the form of ooo , then you should clear the form once it is added, and also change the color of button , it looks like it is disabled.
> * [ ]  the issue is not in allowing permission , the only issue which I can see is the alert message which we show, it should just say that please allow the permission for camera , that's it.
> * [ ]  At bottom nav bar the section of particular home icon and text is too small , it should be bigger (we can adjust it with padding)
> * [ ]  we should move the logout button and update option  under profile avatar.
> * [x]  We should remove noteworthy contributions, it is not needed.
> * [ ]  check the response time of the api of all tasks and active tasks
> * [ ]  fix the loader and response time while fetching active tasks.

ETA:- 12/11/23
