### ISSUE TITLE
FAQs

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#234]

**Comment by harshitadatra** [comment]
### Fetch branch which was pushed from the Forked Repo to the remote repo.
  error occurred -  fatal: couldn't find remote ref _branch name_

 **This error is caused when you want to fetch a branch being pushed from a forked repo.**

   To fetch this branch try the below git commands in order

1. Check the current configured remote repo for our fork.
           `  git remote -v`

- If we haven't configured a remote that points to the upstream repo, we will get

example-
![Screenshot2](https://github.com/Real-Dev-Squad/mobile-app/assets/57798468/08f8ebd0-e7b8-4f7f-97e0-9b556b7c97a7)


2. Add a new remote upstream repo that will be synced with the origin repo.
`git remote add upstream <original-repo-url>`
`original-repo-url` - Here the original repo URL will be the URL of rds mobile app present on GitHub
![Screenshot 6](https://github.com/Real-Dev-Squad/mobile-app/assets/57798468/63180f1a-78c0-40e3-b88b-655945c72044)



3. Check if the new upstream has now been added.
`git remote -v`
    here you will notice
        - origin _fork-repo-url_ (fetch) 
        - origin _fork-repo-url_ (push)
        -  upstream _original-repo-url_ (fetch) 
        - upstream _original-repo-url_ (push)
 example -
![Screenshot3](https://github.com/Real-Dev-Squad/mobile-app/assets/57798468/01543d59-718e-4334-b0c1-7a56b5713611)

4. Fetch data from the upstream.
`git fetch upstream`

5. You will see in the command line that we have fetched the branches on the upstream repo, including the target branch.
`git checkout branch-name`

**Comment by harshitadatra** [comment]
### **Failed to launch emulator**
If you are facing this type of error while doing `npm run android` or` yarn run android`

![screenshot10](https://github.com/Real-Dev-Squad/mobile-app/assets/57798468/57299567-653f-4f5c-a0c8-98a44ca0cab3)

_solution_
1. Open android studio > AVD Manager > Actions (click the bottom icon) > Select Cool Boot Now.
![ss11](https://github.com/Real-Dev-Squad/mobile-app/assets/57798468/7cf0bfcb-3b7b-458b-be0a-e5186ed69495)

**Comment by harshitadatra** [comment]
### Development server returned 500 response error code

![ss12](https://github.com/Real-Dev-Squad/mobile-app/assets/57798468/31f0946a-5984-404f-be4e-61dc2e17495c)

_Solution_
1. cd android
2. ./gradlew clean
3. Delete node modules and install node modules again by running npm install
4. yarn run android

**Comment by ShivangiTiwari10** [comment]
**How to Raise Pull request**
1.Fork GitHub repository ,
2.After forking, clone your forked repository to your local machine by typing  
git clone <https  of forked repo>,
in VS code terminal

3.You should navigate into the directory of your cloned repository using the cd command.

4.Common default branch names are "main," "master," or "develop." You should check the repository's documentation or settings to confirm the default branch name

5.Create a New Branch  for your changes
git checkout -b <your branch name>

6.Make changes to the code  then Commit Your Changes using these commands:
git add .
git commit -m "Your commit message here"

7.Push your branch to GitHub : 
git push origin <branch-name>

8.Checkout on GitHub repo: in right side we will see 
compare & pull request   
![8jEby](https://github.com/Real-Dev-Squad/mobile-app/assets/123884896/a3c175d6-bf0e-492a-9d5d-1dc4310109d2)

9.Click on that and You’ll come to a page that says “Compare changes”
![pull-request-compare](https://github.com/Real-Dev-Squad/mobile-app/assets/123884896/0546867b-d18b-460b-b927-40d44df24799)

10.To create a pull request, you want to set the base and compare branches to the following:

base: branch you want to merge to
compare: branch you want to merge from

11.Provide a clear and concise title and description for your pull request. Explain what your changes do and why they are necessary
![pull-request-open](https://github.com/Real-Dev-Squad/mobile-app/assets/123884896/8795ddf0-6f58-4221-afe4-292d8a439457)

12.Once you've filled out the pull request description, click the "Create pull request" button
