### ISSUE TITLE
API Error Handling in App Issue

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#235]
We have encountered issues related to API error handling in our application that need attention and resolution. This issue ticket is being created to document and track these problems.

**Comment by mohammadkhizerkhan** [comment]
Hi @ankushdharkar @shreya-mishra 

i want to extension for this issue.
next ETA would be 15oct.
It seems that this issue getting small additional requirement so i'm listing down all the tasks which i need to do in this task.

- [x] Storing user's data globally with token.
- [x] Wrapper functions for calling the api's.
- [x] Configuring token in api's which are required(planning to handle this in axios config level). and testing thoroughly.
- [ ] Creating UI for api failure and network issue.
- [ ] Migrating few states from useContext to redux saga.
