### ISSUE TITLE
[Enhancement]: Setup the issue description template for contributor

### ISSUE THREAD

**Issue by samyakshah3008** [RealDevSquad/mobile-app#246]
## Description: 

- Currently any new user who comes up to this repository and reports a new issue ticket, we don't have a template. For a better user and contributor experience, shall we add a template for ease process?

## Potential Solution: 

- Let's setup a GitHub actions for the same? Or else we can create a md file and from settings we can manually mark that file as template. Let's discuss more on it.

**Comment by samyakshah3008** [comment]
I would like to work on this! 🚀 
Cc: @shreya-mishra

**Comment by shreya-mishra** [comment]
sure ! let's add a readme first and then will move to github actions

**Comment by samyakshah3008** [comment]
Thank you @shreya-mishra 🚀 
Will raise a PR before 18th September

**Comment by samyakshah3008** [comment]
This issue is completed with PR https://github.com/Real-Dev-Squad/mobile-app/pull/253 merged. 
Hence closing it. 
Cc: @shreya-mishra
