### ISSUE TITLE
[Design Doc] for QR Scanner Feature

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#249]
### Overview
Currently, users have to manually enter their GitHub credentials in the mobile app to sign in.

Signup with GitHub should redirect to the web browser and ask for the login details and then redirect back to our Mobile app
https://github.com/Real-Dev-Squad/mobile-app/issues/142

This can be a tedious process because a lot of people didn't sign into GitHub on the mobile app. To make the sign-in process smoother and more efficient, we propose the implementation of QR code scanning for sign-in in the mobile app.

With this feature, users will be able to scan a QR code from the my-site website using their mobile camera, which will automatically fill in their login credentials in the mobile app provided that they should be logged in to my-site, making the sign-in process much easier and faster. This will improve the overall user experience and increase user engagement with our app.

Implementation of this feature will require updates to the mobile app, the website, and the backend. We will need to develop a QR code generator for the website, as well as a QR code scanner for the mobile app. The scanner will need to be able to decode the QR code and extract the user's login credentials securely.

We believe that this feature will be highly beneficial for our users and will set our app apart from competitors. We look forward to working on this feature and improving the user experience of our app.

## Technical Implementation

    **QR Code Scanning and POST Request**
      

       - Scan a QR code on the website (my-site).

        - Initiate a POST request from the website to an API endpoint, sending the device ID and user ID in the request body.

    **Display Proceed Button:**
       - Upon successful POST request, display a "Proceed" button.

    **Mobile Popup Display:**
       - On the mobile device, show a popup instructing the user to "Verify on my-site" by clicking a "Verify" button.

    **Mobile PATCH Request:**
        -If the user selects "Yes" on the mobile, send a PATCH request to an API endpoint with "authorized" as the data. If "No" is selected, send "not_authorized."

    **Token Generation for Authorization:**
       - Upon receiving "authorized," generate an RDS session cookie (token) on the server.

    **Proceed with GET API Call:**
       - If the user presses "Proceed" on the mobile, make a GET API call to retrieve a token for user sign-in.

These steps outline the technical process of scanning a QR code, initiating requests, displaying popups, and managing authorization and token generation for user sign-in.

### Sign in with QR Code flow(Old Flow)

```mermaid
sequenceDiagram
    participant User as User
    participant RDS_App as RDS App
    participant RDS_Web as RDS Web
    participant RDS_Backend as RDS Backend

    User->>RDS_App: Clicks on Sign in with QR Code button
    User->>RDS_Web: Opens QR code on my.realdevsquad.com/mobile
    User->>RDS_App: Scans QR code on RDS App
    RDS_App->>RDS_App: Show two buttons with message "Your device info added successfully"
    User->>RDS_App: Clicks on "Ok" button
    RDS_App->>RDS_Backend: Sends POST request with device id
    User->>RDS_Web: Click on "Verify Status" button 
    RDS_Web->>RDS_Backend:Calls GET to https://api.realdevsquad.com/auth/device
    RDS_Web-->>User: Shows alert message "Are you sure you are the one who scanned this QR code? Do you want to proceed?"
    User->>RDS_Web: Clicks on "Yes" button
    RDS_Web->>RDS_Backend: Sends POST request with login status
    RDS_Web->>RDS_Backend: Calls GET to https://api.realdevsquad.com/auth/qr-code-auth/authorization_status/AUTHORIZED
    RDS_Backend-->>RDS_Web: Verification
    RDS_Web-->>User: Shows message "You are successfully logged in"
    User->>RDS_App: Clicks on "Done" button
    RDS_App->>RDS_App: Completes login process

```
### Sign in with QR(Added steps to get token in local storage in RDS App)

```mermaid
sequenceDiagram
    participant User as User
    participant RDS_App as RDS App
    participant RDS_Web as RDS Web
    participant RDS_Backend as RDS Backend

    User->>RDS_App: Clicks on Sign in with QR Code button
    User->>RDS_Web: Opens QR code on my.realdevsquad.com/mobile
    User->>RDS_App: Scans QR code on RDS App
    RDS_App->>RDS_App: Show two buttons with message "Your device info added successfully"
    User->>RDS_App: Clicks on "Ok" button
    RDS_App->>RDS_Backend: Sends POST request with device id
    User->>RDS_Web: Click on "Verify Status" button 
    RDS_Web->>RDS_Backend: Calls GET to https://api.realdevsquad.com/auth/device
    RDS_Web-->>User: Shows alert message "Are you sure you are the one who scanned this QR code? Do you want to proceed?"
    User->>RDS_Web: Clicks on "Yes" button
    RDS_Web->>RDS_Backend: Sends POST request with login status
    RDS_Web->>RDS_Backend: Calls GET to https://api.realdevsquad.com/auth/qr-code-auth/authorization_status/AUTHORIZED
    RDS_Backend-->>RDS_Web: Verification
    RDS_Web-->>User: Shows message "You are successfully logged in"
    
    %% New Step: Obtain and Save Token in Mobile App
    RDS_App->>RDS_Backend: Calls an API to obtain an authentication token
    RDS_Backend-->>RDS_App: Responds with the authentication token
    RDS_App->>RDS_App: Stores the token locally on the mobile device
    
    User->>RDS_App: Clicks on "Done" button
    RDS_App->>RDS_App: Completes login process

```
<details>
## <summary>Steps Description</summary>

**Step 1: Clicks on Sign in with QR Code button**
- **Description**: The user initiates the login process by clicking on the "Sign in with QR Code" button in the RDS mobile application.
- **Inputs**: User interaction with the mobile application.
- **Outputs**: Initiates the QR code scanning process.

**Step 2: Opens QR code on my.realdevsquad.com/mobile**
- **Description**: The user opens a QR code on the my.realdevsquad.com/mobile web page, which will be scanned by the mobile app for authentication.
- **Inputs**: User's action to open the URL.
- **Outputs**: Displays the QR code on the web page.

**Step 3: Scans QR code on RDS App**
- **Description**: The user uses the RDS mobile app to scan the QR code displayed on the web page for authentication.
- **Inputs**: QR code data from the web page.
- **Outputs**: Initiates the login process with the scanned data.

**Step 4: Show two buttons with message "Your device info added successfully"**
- **Description**: The RDS mobile app displays a message to the user indicating that the device info has been added successfully and provides two buttons.
- **Inputs**: Confirmation of successful QR code scanning.
- **Outputs**: Displays the message and buttons.

**Step 5: Clicks on "Ok" button**
- **Description**: The user clicks on the "Ok" button in the RDS mobile app after seeing the success message.
- **Inputs**: User interaction with the mobile app.
- **Outputs**: Initiates a POST request to the backend with the device ID.

**Step 6: Sends POST request with device id**
- **Description**: The RDS mobile app sends a POST request to the RDS backend with the device ID for further processing.

**Step 7: Click on "Verify Status" button**
- **Description**: The user initiates the verification process by clicking on the "Verify Status" button in the RDS web application.
- **Inputs**: User interaction with the web application.
- **Outputs**: Proceeds to verify the login status.

**Step 8: Calls GET to https://api.realdevsquad.com/auth/device**
- **Description**: The RDS web application sends a GET request to the backend API at the specified URL to retrieve information about the logged-in device.
- **Inputs**: User's action to verify the device status.
- **Outputs**: Retrieves device information from the backend.

**Step 9: Shows alert message "Are you sure you are the one who scanned this QR code? Do you want to proceed?"**
- **Description**: The RDS web application presents an alert message to the user, seeking confirmation before proceeding with the login process.
- **Inputs**: Device information retrieved from the backend.
- **Outputs**: Displays the confirmation message.

**Step 10: Clicks on "Yes" button**
- **Description**: The user confirms their identity by clicking on the "Yes" button in response to the alert message.
- **Inputs**: User interaction with the web application.
- **Outputs**: Initiates further communication with the backend.

**Step 11: Sends POST request with login status**
- **Description**: The RDS web application sends a POST request to the backend to update the login status.
- **Inputs**: User's confirmation.
- **Outputs**: Sends a request to update the status.

**Step 12: Calls GET to https://api.realdevsquad.com/auth/qr-code-auth/authorization_status/AUTHORIZED**
- **Description**: The RDS web application sends a GET request to the backend API to check the authorization status after the user confirms.
- **Inputs**: User's action to proceed.
- **Outputs**: Retrieves authorization status from the backend.

**Step 13: Verification**
- **Description**: The RDS backend verifies the user's identity and authorization status based on the received requests and data.
- **Inputs**: Requests from the mobile and web applications.
- **Outputs**: Verifies the user and device status.

**Step 14: Shows message "You are successfully logged in"**
- **Description**: The RDS web application displays a success message to the user, indicating a successful login.
- **Inputs**: Confirmation of successful verification.
- **Outputs**: Displays the success message.

**Step 15: Obtains and Stores Authentication Token**
- **Description**: After successful verification, the RDS web application calls an API to obtain an authentication token.
- **Inputs**: Confirmation of successful login.
- **Outputs**: Receives an authentication token from the backend.

**Step 16: Stores Token in Local Storage**
- **Description**: The RDS mobile application stores the received authentication token locally on the mobile device, typically in local storage or secure storage for future API authentication.
- **Inputs**: Received authentication token.
- **Outputs**: Stores the token securely on the device.

**Step 17: Clicks on "Done" button**
- **Description**: The user finalizes the login process by clicking on the "Done" button in the RDS mobile application.
- **Inputs**: User interaction with the mobile application.
- **Outputs**: Completes the login process.

</details>

## Timeline

This design will be implemented as a part of the QR functionality. The timeline for implementation will be determined based on project priorities.

**Comment by yesyash** [comment]
- Can we do the authentication and authorization part from the mobile app where the flow would be something like: 
    -> generate QR code from web app -> scan the code on mobile app -> perform the authentication with device id -> run authorization (`GET to https://api.realdevsquad.com/auth/qr-code-auth/authorization_status/AUTHORIZED`) -> store the token -> logged in.

**Comment by shreya-mishra** [comment]
> * Can we do the authentication and authorization part from the mobile app where the flow would be something like:
>       -> generate QR code from web app -> scan the code on mobile app -> perform the authentication with device id -> run authorization (`GET to https://api.realdevsquad.com/auth/qr-code-auth/authorization_status/AUTHORIZED`) -> store the token -> logged in.

this is beta release , will look into cryptography and more user friendly in which user don't have to click again and again will look in v1.
