### ISSUE TITLE
RFC: Open RDS app from any hosted website via popup

### ISSUE THREAD

**Issue by dhruv036** [RealDevSquad/mobile-app#260]
**Steps**    
1. Navigate to the hosted website (in our case my-site and www site).
2. I should show a popup open the RDS app via a popup.

On loading of the website it should show a popup, and the RDS app should open if the user wants.

**Comment by dhruv036** [comment]
Hi @shreya-mishra please assign this to me, ETA would be 24/09/2023

**Comment by shreya-mishra** [comment]
Please get it assigned via tejas or ankush!
