### ISSUE TITLE
Fix TestCases which are failing on Develop

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#304]
### Issue Description

Run `yarn run test` command and fix the test cases which are failing on develop.

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by ShivangiTiwari10** [comment]
Please assign this task to me
