### ISSUE TITLE
Update Form for Goals

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#311]
Add label dropdown in goals form which will show all the groups which RDS server has. 

**Backend api to get all the groups** : https://api.realdevsquad.com/discord-actions/groups

**Comment by ashifkhn** [comment]
@shreya-mishra  Can you please elaborate this issue?

**Comment by shreya-mishra** [comment]
For Goals , we just need members in a drop-down as we cant assign a specific task to groups.
we decided to make notify service in different tab
