### ISSUE TITLE
UI fixes in profile page

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#315]
### Issue Description

- [ ] Alignment fix for tabs : Noteworthy, active and all
- [ ] the selected tab should be bold and all other should be grey.
- [ ] on click of tabs it should be swipable.

### Expected Behavior

[Describe what should happen when this issue is resolved.]

### Current Behavior

[Explain what currently happens when this issue is encountered.]

### Screenshots
![WhatsApp Image 2023-10-25 at 9 05 38 PM](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/33063266-c6d7-4361-8901-d8d1c6c7cb75)

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by ShivangiTiwari10** [comment]
Please assign this task to me
