### ISSUE TITLE
fix the loader and response time while fetching active and all  tasks.

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#327]
**Fix**

- [ ] on Installation of the app , the title shows @undefined 
- [ ] Active screen shows nothing  despite I have the active tasks. 
- [ ] please add the loader during fetching. 
- [ ] fix the response time of the Active as well as All tasks.

![WhatsApp Image 2023-11-18 at 1 09 13 PM](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/4ea69f09-5067-4036-b5fe-8ec9247ebb72)

**Comment by yesyash** [comment]
@shreya-mishra i had a few doubts regarding the task.

> on Installation of the app , the title shows @undefined
- three questions here:
    - are we referring to the app installing screen?
    - what should we show instead of `@undefined`, `Real Dev Squad`?
    - in the screenshot attached i see `@undefined` below the username are they related by any chance? should this be fixed as well in this ticket?

>  fix the loader and response time while fetching
- what do we mean by fixing response time?

**Comment by shreya-mishra** [comment]
- on installation of the app we should show the discord username, - @shreya (discord username)- 
- The response is coming so late, it should either get fix or loader should be
there unless the response is not thereThankyouShreya*
