### ISSUE TITLE
Profile screen All task details screen

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#329]
### Issue Description

Profile Section Update - clicking on All tasks section , which will open the new screen name named all task detail screen. Where we can give progress updates as well.

### Expected Behavior

it should show the screen of status m -site screens

### Current Behavior

no screen yet

### Screenshots

![image](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/9a916431-fd8e-4e66-87c4-5905a83adeb3)
![image](https://github.com/Real-Dev-Squad/mobile-app/assets/61110378/6892ffdf-b7cc-47a2-82cc-01af4268938f)

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by JAYATEJA04** [comment]
@shreya-mishra please assign me this task.

**Comment by shreya-mishra** [comment]
> @shreya-mishra please assign me this task.

already taken by Dhruv.

**Comment by dhruv036** [comment]
@shreya-mishra 
Task Breakdown:-

- [ ] UI 3 Days:- Need to create multiple screens and navigation to this screen with mocking dummy data.
   - [ ] Screen for task detail.
   - [ ]  Screen for update task.
- [ ] API integration 2 Days:- Need to integrate multiple API with interdependency.
- [ ] Testing 3 Days:- Need to learn how to write unit test and integration test and implement that.
- [ ] Review and Buffer 3 Days:- Need 2 days to review, approval and 1 day for buffer.

**Comment by dhruv036** [comment]
@shreya-mishra ETA: 25/11/23
