### ISSUE TITLE
Mobile app enhancement

### ISSUE THREAD

**Issue by skv93-coder** [RealDevSquad/mobile-app#389]
### Issue Description

- [ ] `Started on` and `Ends on` for task are showing as nan-nan-nan on task details screen.
- [ ] The link does not have an empty state.
- [ ] The app takes a noticeable time to render task details data.

### Expected Behavior

[Describe what should happen when this issue is resolved.]

### Current Behavior

[Explain what currently happens when this issue is encountered.]

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

https://github.com/Real-Dev-Squad/mobile-app/assets/68867418/f445ca1f-2f7e-4c5b-b49a-8c721146da17

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by skv93-coder** [comment]
Solution for above problems
1. Add NA as an empty state for the link
2. Add empty state of DD/MM/YYYY
for dates
3. Remove compulsory API call for task/details/:id. Instead, use if the task is already present in the tasks array (fetched by  /task API) to render details. 
**The above changes will be done for only the Android app.**

**Comment by shreya-mishra** [comment]
Removing the api calls  will not help.

**Comment by skv93-coder** [comment]
> Removing the api calls will not help.
It will surely save time when the user is coming from the task list screen.

**Comment by shreya-mishra** [comment]
Try some easy method, we don't have a loader on the task Detail screen, so why not start with that?
