### ISSUE TITLE
Issues in current flow of Goals App Basic Flow

### ISSUE THREAD

**Issue by ashifkhn** [RealDevSquad/mobile-app#390]
### Issue Description

While observing the whole flow noticed some of the below issues in Goals app basic flow

- Assigning tasks to someone else is visible to goals screen
- goals form text font issue
- Goals icon color issue

### Expected Behavior

- [x] Creating a new task and assigning it to someone else shows it to logged in user.
- [x] typing anything in goals form, it is kinda disable,
- [x] The pickup date isn't visible even after choosing that.
- [x] Goals icon is not visible
- [x] the bug on choosing that member from drop-down, it should be scrolled down automatically

### Current Behaviour
Above issues need to be fixed.

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by shreya-mishra** [comment]
please describe the issue properly.

**Comment by shreya-mishra** [comment]
**These should be todos for Goals App**
- [ ] Are we getting all todos from API and I don't think POST API is working properly? Please mention the reason before jumping to any solution.
- [ ] When I am typing anything in goals form, it is kinda  disable, please fix this
- [ ] The pickup date isn't visible even after choosing that.
- [ ] Goals icon is not visible
- [ ] Please fix the bug on choosing that member from drop-down, it should be scrolled down automatically
