### ISSUE TITLE
No Data connection should be handle in offline state

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#396]
### Issue Description

No data connection case is not handled properly I think.
### Expected Behavior

At offline state the response should be in cache , atleast downloaded data should be visible

### Current Behavior

functionality not exist
### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by ashifkhn** [comment]
Should I make a screen asking user to turn on data and reload the app?

**Comment by ashifkhn** [comment]
One approach is to cache relevant data locally on the device so that it's accessible even when the app is offline. We can use libraries like AsyncStorage (for small amounts of data) or SQLite (for larger datasets) to store data locally. When the app is offline, it can fetch data from the local storage instead of making network requests.

**Comment by ashifkhn** [comment]
Or If certain features or data cannot be accessed offline, we can display an offline screen to inform users about the limited functionality. This screen can provide helpful information, such as instructions on how to reconnect to the internet or suggestions for features that are available offline.

**Comment by shreya-mishra** [comment]
> One approach is to cache relevant data locally on the device so that it's accessible even when the app is offline. We can use libraries like AsyncStorage (for small amounts of data) or SQLite (for larger datasets) to store data locally. When the app is offline, it can fetch data from the local storage instead of making network requests.

To persist our data even if we are offline we can use AsyncStorage as it is already installed, and for API calls we need to build an offline error screen.
