### ISSUE TITLE
Layout breaks in orientation

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#397]
### Issue Description

Layout breaks if I rotate orientation. I can't scroll from some sections(eg. can scroll in the tasks section, but can't scroll from above in the profile section.)

### Expected Behavior

App should be responsive in small/big screens
### Current Behavior

[Explain what currently happens when this issue is encountered.]

### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by ashifkhn** [comment]
Can we just lock the app in portrait mode?

**Comment by shreya-mishra** [comment]
> Can we just lock the app in portrait mode?
Already told the same solution to Shubham Sharma
