### ISSUE TITLE
Authentication using github

### ISSUE THREAD

**Issue by palakgupta2712** [RealDevSquad/mobile-app#4]
![Auth with github](https://user-images.githubusercontent.com/61227144/149637230-96bdf03a-252c-4dc8-b3fa-4ab41a7d9a8c.png)

**Comment by rushi-173** [comment]
As discussed I will be working with @shaksham08 on this task.

**Comment by shreya-mishra** [comment]
ok @rushi-173 What's the status ?

**Comment by shreya-mishra** [comment]
@rushi-173 Since you have not finished this task so I am reassigning to somebody else .

**Comment by shreya-mishra** [comment]
@ganshul34 
ETA given : Thursday(10/02)
