### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#44]
**Refactoring the code of Profile screen page.**

1.  separate the logic of camera functionality in separate file
2.  Remove constants and add them to constant folder.

**Comment by DeRaowl** [comment]
@shreya-mishra can you assign this tsk to me

**Comment by shreya-mishra** [comment]
> @shreya-mishra can you assign this tsk to me

Assigned! . Can you please give ETA for the same ?

**Comment by rushabh-t** [comment]
Assign it to me.

**Comment by shreya-mishra** [comment]
@rushabh-t  please clone it and let me know if you need any help with this .

**Comment by shreya-mishra** [comment]
@DeRaowl do you also want to help him ? if yes pls do it as we have to deliver it this as early as possible .

**Comment by DeRaowl** [comment]
Sure @shreya-mishra , @rushabh-t let me know if you face any issues.

**Comment by rushabh-t** [comment]
> @rushabh-t please clone it and let me know if you need any help with this .

Sure, I will text on the discord channel if I need any help

**Comment by shreya-mishra** [comment]
@rushabh-t whats the progress?
