### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by pankajjs** [RealDevSquad/mobile-app#464]
### Issue Description
Tests are failing on executing test command.

### Expected Behavior
Every test should pass.

### Current Behavior
Tests are failing while executing test command.

### Screenshots
<img width="762" alt="Screenshot 2024-10-09 at 10 02 54 PM" src="https://github.com/user-attachments/assets/f9e3463d-56b5-41ad-b17e-158b86f1b555">

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by prankurpandeyy** [comment]
@shreya-mishra assign this to me
