### ISSUE TITLE
Remove Skipped Tests and Ensure Test Suite is Running Fully

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#470]
### Issue Description

Remove all instances of skipped tests in the codebase (tests marked with .skip or similar), and ensure that all tests are running as part of the test suite. This task also includes identifying any issues or failures with previously skipped tests and fixing them if necessary.

**Locate Skipped Tests:**

Search for any tests in the codebase that are marked as skipped (e.g., it.skip, test.skip, describe.skip, etc.).
Remove Skip Flags:

Remove .skip or equivalent flags from all test cases.

**Run the Test Suite:**

Execute the entire test suite using the appropriate test command (e.g., npm test, pnpm test, yarn test).

**Address Failing Tests:**

Investigate and fix any test failures that occur after re-enabling the skipped tests.
Verify Successful Test Run:

Ensure that all tests pass and the suite completes without any skips.
Update Documentation (if needed):

Ensure that test-related documentation reflects any updates or changes, including the resolution of previously skipped tests.### Screenshots

[If applicable, add screenshots or images that help illustrate the issue. You can use the following Markdown syntax to embed images:]

### Environment

- Operating System: [e.g., Windows, macOS, Linux]
- Browser (if applicable): [e.g., Chrome, Firefox, Safari]
- Version of Software/Project: [e.g., v1.0.0]

### Additional Information

[Include any additional context, logs, or details that might be helpful in addressing the issue.]

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.

---

Thank you for contributing to our project! We appreciate your help in improving it.

📚 See [contributing instructions](https://github.com/samyakshah3008/mobile-app/blob/develop/CONTRIBUTING.md).

**Comment by abhisheksharmayt** [comment]
Could you please assign this to me?

**Comment by iamitprakash** [comment]
Reponed because of multiple PR on this issues
