### ISSUE TITLE
v1 my-site: home tab

### ISSUE THREAD

**Issue by palakgupta2712** [RealDevSquad/mobile-app#5]
- Users can click on the button to change their status to:
   - active, or
   - idle
  
- We have to implement these for my site home tab

<img width="228" alt="image" src="https://user-images.githubusercontent.com/61227144/149637863-55f37da0-1ae9-4bc4-9899-92e0135d8d7d.png">

<img width="233" alt="image" src="https://user-images.githubusercontent.com/61227144/149637839-21b76952-6744-420d-b1da-68c09915e6c2.png">

**Comment by vinayak-trivedi** [comment]
This task was completed
