### ISSUE TITLE
v1 my-site: profile page

### ISSUE THREAD

**Issue by palakgupta2712** [RealDevSquad/mobile-app#6]
- Users will have to fill in a 3-step form:
   - [ ] Personal Details: 
     - First Name
     - Last Name
     - Username
     - Email id
     - Next Button
    
  - [ ] Accounts Details: 
       - Company Name/ College Name
       - Designation / Branch
       - Experience 
       - LinkedIn Id
       - Twitter Id
       - Website
       - Next Button
       - Back Button 
       
   - [ ] Upload Image: 
     - Card for uploading user profile image
     - Upload Image Button
     - Submit button

For design refer
- https://www.figma.com/file/i5DNFdpQc11ZJ26zU7goFh/RDS-MOBILE-APP?node-id=0%3A1
- https://my.realdevsquad.com/profile

**Comment by vinayak-trivedi** [comment]
we are not having profile page like this.
