### ISSUE TITLE
v1 my-site: notification page

### ISSUE THREAD

**Issue by palakgupta2712** [RealDevSquad/mobile-app#7]
- Users will see in-app notifications 

![Notification](https://user-images.githubusercontent.com/61227144/149636853-d5ae4aa2-4960-4b94-b432-828b16f01ab1.png)

**Comment by priyanshk20** [comment]
@palakgupta2712 We will have to create two tasks for this, one screen will be the notification screen(which will render the notification), the other screen will be no-notification screen, that will be constant. So keepiig it as a separate screen will be better.
