### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#81]
Feature Test 

- [x] Github Auth 
- [ ] Home Screen  component
- [ ]  Profile Screen component
- [ ] Mock data test for Home screen APIs
- [ ] Mock data test for Profile screen APIs

**Comment by shreya-mishra** [comment]
Changed the whole flow of Github Auth so, we need to rewrite the test cases.

**Comment by sakshambhatt** [comment]
Hello Shreya, I am willing to take this up. I have completed the setup on my machine and brushing up testing for it as well. :weight_lifting_man:

**Comment by sakshambhatt** [comment]
@shreya-mishra , could you please confirm if I have understood the above tasks correctly?

## githb auth test
should I write tests for AuthContext or for AuthScreen or in AuthScreen specifically for getUserData function? 

## homescreen test (already exists, rewrite?)
changing OOO status	

## profile screen component
modal, picture changes

## mock data tests for 
#### home screen API
setting OOO status API?
#### profile screen API
photo upload API?

**Comment by shreya-mishra** [comment]
> @shreya-mishra , could you please confirm if I have understood the above tasks correctly?
> 
> ## githb auth test
> should I write tests for AuthContext or for AuthScreen or in AuthScreen specifically for getUserData function?
> 
> ## homescreen test (already exists, rewrite?)
> changing OOO status
> 
> ## profile screen component
> modal, picture changes
> 
> ## mock data tests for
> #### home screen API
> setting OOO status API?
> 
> #### profile screen API
> photo upload API?

You have to rewrite the complete test because the auth flow has changed completly.

**Comment by sakshambhatt** [comment]
getUserData-tests removed because I checked out my branch from apiIntegration/home instead of develop.
added Util-test.ts

**Comment by sakshambhatt** [comment]
Util-tests have been completed, HomeScreen has 1 API call which is updateStatus. So, Mock data test for Home screen APIs is done

**Comment by sakshambhatt** [comment]
Fixed loggedInUserData being set to null after successful login, finally able to see the app screens instead of website in the webview container

Bug resolution: 
1. getUserData was being called with all the urls, so even after setting loggedInUserData correctly, it would get called with some url which would make it return null and loggedInUserData to become null as well.
2. After calling getUserData only when the url is redirect-url, I observed that the problem still persisted. That was because the userData response object could come without any profile.url attribute, and that was causing getUserData functions to fail, leading to loggedInUserData null again. So I added optional chaining to getUserData and it is working now.

**Comment by shreya-mishra** [comment]
> Fixed loggedInUserData being set to null after successful login, finally able to see the app screens instead of website in the webview container
> 
> Bug resolution:
> 
> 1. getUserData was being called with all the url, so even after setting loggedInUserData correctly, it would get called with some url which would make it return null and loggedInUserData to become null as well.
> 2. After calling getUserData only when the url is redirect, I observed that the problem still persisted. That was because the userData response object could come without any profile.url attribute, and that was causing getUserData functions to fail, leading to loggedInUserData null again. So I added optional chaining to getUserData and it is working now,

Have you raised the PR ?

**Comment by sakshambhatt** [comment]
> > Fixed loggedInUserData being set to null after successful login, finally able to see the app screens instead of website in the webview container
> > Bug resolution:
> > 
> > 1. getUserData was being called with all the url, so even after setting loggedInUserData correctly, it would get called with some url which would make it return null and loggedInUserData to become null as well.
> > 2. After calling getUserData only when the url is redirect, I observed that the problem still persisted. That was because the userData response object could come without any profile.url attribute, and that was causing getUserData functions to fail, leading to loggedInUserData null again. So I added optional chaining to getUserData and it is working now,
> 
> Have you raised the PR ?

Yes, I have raised the PR. Please take a look: 
https://github.com/Real-Dev-Squad/mobile-app/pull/100

**Comment by shreya-mishra** [comment]
Merged to [PR 90](https://github.com/Real-Dev-Squad/mobile-app/pull/90)

**Comment by sakshambhatt** [comment]
Using Context for Auth is a very common practice. Testing it is pretty straightforward as well [codesandbox](https://codesandbox.io/s/testing-usecontext-lu3hco?file=/__tests__/App-test.tsx).
But the useEffect in the AuthProvider is causing trouble, as it fetches loggedInUserData from AsyncStorage and then triggers a re-render of the AuthProvider component. While testing, the assertion is already called when useEffect has not even had a chance to re-render with the data from store.
1. Either useEffect in ContextProvider is a code smell
2. Or testing such a scenario should be handled in a different manner than currently being done.

```
test('when idle, changeStatus to active', async () => {
    // store data in mock async storage as idle
    await AsyncStorage.clear();
    await storeData(
      'userData',
      JSON.stringify({ ...dummyLoggedInUserData, status: Strings.IDLE }),
    );

    const { getByText, getByTestId } = renderHomeScreen();
    getByText(Strings.Idle_Text);
    const changeStatusBtn = getByTestId('changeStatusBtn');

    mockedAxios.patch.mockResolvedValue({
      config: { data: { status: Strings.ACTIVE } },
    });
    fireEvent.press(changeStatusBtn);
    await waitFor(() => expect(mockedAxios).toHaveBeenCalledTimes(1));
  });
```

![image](https://user-images.githubusercontent.com/33225002/178644131-464d174c-e084-408f-9dee-06f3cdb9bea1.png)

**Comment by sakshambhatt** [comment]
HomeScreen component tests are done. Should I raise a PR for them? @shreya-mishra
