### ISSUE TITLE
Loader

### ISSUE THREAD

**Issue by shreya-mishra** [RealDevSquad/mobile-app#84]
Make one Loader component and add the same wherever needed.

**Comment by rajat-mehra05** [comment]
I'd like to take up this issue, though I've no prior knowledge of react native. Can I still take this issue ?

**Comment by DeRaowl** [comment]
Yes you can work on this. Can you let me know the ETA?

**Comment by rajat-mehra05** [comment]
ETA- April 24. Please assign this issue to me.

**Comment by rajat-mehra05** [comment]
Hi @shreya-mishra, Tried installing and setting up the react-native and android studio on my system but the system is not compatible. Please assign this issue to someone else.

**Comment by vvaibhavdesai** [comment]
Hey @shreya-mishra  I'll take up this issue with the ETA on 27th

**Comment by shreya-mishra** [comment]
> Hey @shreya-mishra I'll take up this issue with the ETA on 27th

assigned

**Comment by vvaibhavdesai** [comment]
The ticket talks about putting the loader wherever needed are the places where loaders are needed to be added commented? 
If not then can we please have the file names listed in this ticket?

**Comment by shreya-mishra** [comment]
Yea it should be during the authentication page when we switch to the web page  I want at that time don't redirect just set loader - true so that we don't see the web page.

**Comment by vvaibhavdesai** [comment]
Hey @shreya-mishra here is the link: https://github.com/Real-Dev-Squad/mobile-app/pull/89  to pr please let me know if you need anything more

**Comment by shreya-mishra** [comment]
Merged the PR
